import type { Job } from "./types/Job";

export const mockJobs: Job[] = [
  {
    id: "1",
    company: "Google",
    title: "Software Engineer Intern",
    platform: "LinkedIn",
    date: "Jun 26, 2026",
    riskLevel: "Low",
    status: "Screening",
  },
  {
    id: "2",
    company: "CloudNest",
    title: "Cybersecurity Analyst Intern",
    platform: "Handshake",
    date: "Jun 25, 2026",
    riskLevel: "Medium",
    status: "No response",
  },
  {
    id: "3",
    company: "BrightTech",
    title: "Frontend Developer Intern",
    platform: "Indeed",
    date: "Jun 24, 2026",
    riskLevel: "High",
    overallScore: 82,
    scanDate: "Jun 24, 2026",
    dateApplied: "Jun 24, 2026",
    status: "Applied",
    topFinding: "Apply link redirects to an unrelated domain",
    categories: { phishing: 82, fakeRecruiter: 65, scam: 74, ghost: 22 },
    findings: [
      {
        id: "f1",
        severity: "High",
        category: "Phishing",
        title: "Apply link redirects to an unrelated domain",
        evidence: "jobs-apply.net",
        description: "The application button resolves to jobs-apply.net, not brighttech.com.",
        recommendation: "Verify the application link leads to the official company domain before submitting personal information.",
        points: 25,
      },
      {
        id: "f2",
        severity: "High",
        category: "Scam",
        title: "Posting requests SSN before interview",
        evidence: '"Submit your Social Security Number with your application"',
        description: "Job description asks applicants to submit SSN as part of the initial application.",
        recommendation: "Legitimate employers do not request SSNs before an offer stage. Do not submit this information.",
        points: 30,
      },
      {
        id: "f3",
        severity: "Medium",
        category: "Fake recruiter",
        title: "Recruiter email uses a personal domain",
        evidence: "recruiter@gmail.com",
        description: "Contact listed as recruiter@gmail.com rather than a brighttech.com address.",
        recommendation: "Verify the recruiter via BrightTech's official LinkedIn or careers page before responding.",
        points: 15,
      },
      {
        id: "f4",
        severity: "Low",
        category: "Phishing",
        title: "Urgency language detected",
        evidence: '"immediate hire", "apply within 24 hours"',
        description: "Description includes phrases commonly used in fraudulent postings to pressure applicants.",
        recommendation: "Urgency language alone is not conclusive, but is a common pattern in fraudulent postings.",
        points: 8,
      },
    ],
  },
  {
    id: "4",
    company: "Poop",
    title: "Frontend Developer Intern",
    platform: "Handshake",
    date: "Jun 27, 2026",
    riskLevel: "High",
    status: "Ghosted",
  },
  {
    id: "5",
    company: "Poop",
    title: "Backend Developer Intern",
    platform: "Glassdoor",
    date: "Jun 29, 2026",
    riskLevel: "Low",
    status: "Interview",
  },
  {
    id: "6",
    company: "Poop",
    title: "Backend Developer Intern",
    platform: "Glassdoor",
    date: "Jun 29, 2026",
    riskLevel: "Low",
    status: "Applied",
  },
  {
    id: "7",
    company: "Poop",
    title: "Backend Developer Intern",
    platform: "Glassdoor",
    date: "Jun 29, 2026",
    riskLevel: "Low",
    status: "Offer",
  },
  {
    id: "8",
    company: "Poop",
    title: "Backend Developer Intern",
    platform: "Glassdoor",
    date: "Jun 29, 2026",
    riskLevel: "Low",
    status: "Rejected",
  },
  {
    id: "9",
    company: "Poop",
    title: "Backend Developer Intern",
    platform: "Glassdoor",
    date: "Jun 29, 2026",
    riskLevel: "Low",
    status: "Screening",
  },
  {
    id: "10",
    company: "Poop",
    title: "Backend Developer Intern",
    platform: "Glassdoor",
    date: "Jun 29, 2026",
    riskLevel: "Low",
    status: "Applied",
  },
  {
    id: "11",
    company: "Fah",
    title: "Backend Developer Intern",
    platform: "Glassdoor",
    date: "Jun 29, 2026",
    riskLevel: "Low",
    status: "No response",
  },
  {
    id: "12",
    company: "Fah",
    title: "Backend Developer Intern",
    platform: "Glassdoor",
    date: "Jun 29, 2026",
    riskLevel: "Low",
    status: "Ghosted",
  },
];
